wttr.in: handle error

diff --git a/web/wttr.in b/web/wttr.in
--- a/web/wttr.in
+++ b/web/wttr.in
@@ -1,3 +1,8 @@
 #!/bin/sh
 
-curl wttr.in "$1"
+set -e
+
+if ! curl --connect-timeout 2 -s wttr.in/"$1" 2>/dev/null; then
+	echo "$0: failed to connect (missing internet connection?)"
+	exit 1
+fi
